### ISSUE TITLE
QHttpServer compile error

### ISSUE THREAD

**Issue by MingqianYang** [Trojan-Qt5/Trojan-Qt5#105]
When compile **QHttpServer**, it always says" fatal error: ...... No such file or directory "

![Screenshot from 2020-02-27 16-25-46](https://user-images.githubusercontent.com/15353430/75414795-d2c2fe80-597d-11ea-8c7b-85dbbad0dc22.png)

**Comment by TheWanderingCoel** [comment]
Could you try this?
https://github.com/limetext/qml-go/issues/6#issuecomment-288879689

**Comment by PNBRQK** [comment]
I have encountered this problem too.
Maybe have to sit and wait for Debian's upgrade of QT to ver 5.13.x.

**Comment by TheWanderingCoel** [comment]
you can try qtci

**Comment by TheWanderingCoel** [comment]
Closed since QHttpServer is no longer needed
