### ISSUE TITLE
应用程序“trojan-qt5”无法打开。

### ISSUE THREAD

**Issue by reactoa** [Trojan-Qt5/Trojan-Qt5#114]
<img width="420" alt="WX20200228-191859@2x" src="https://user-images.githubusercontent.com/59777291/75544911-e5156900-5a5f-11ea-8c33-af65b779e714.png">

**Comment by TheWanderingCoel** [comment]
尝试:
1) https://www.macbl.com/article/tips/1463
2) sudo spctl --master-disable
3) 右键打开

**Comment by reactoa** [comment]
> 尝试:
> 
> 1. https://www.macbl.com/article/tips/1463
> 2. sudo spctl --master-disable
> 3. 右键打开

其实所有办法都试了，都不行,windows10也不行，还自动给杀了

**Comment by ShineUnM** [comment]
> > 尝试:
> > 
> > 1. https://www.macbl.com/article/tips/1463
> > 2. sudo spctl --master-disable
> > 3. 右键打开
> 
> 其实所有办法都试了，都不行,windows10也不行，还自动给杀了

xattr -c -r /path/to/your/app
