### ISSUE TITLE
Compile qthttpserver error on windows

### ISSUE THREAD

**Issue by MingqianYang** [Trojan-Qt5/Trojan-Qt5#138]
`Microsoft (R) Program Maintenance Utility Version 14.16.27035.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cd src\ && ( if not exist Makefile C:\Qt\Qt5.14.1\5.14.1\msvc2017_64\bin\qmake.exe -o Makefile F:\qthttpserver\src\src.pro ) && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\nmake.exe" -f Makefile

Microsoft (R) Program Maintenance Utility Version 14.16.27035.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cd sslserver\ && ( if not exist Makefile C:\Qt\Qt5.14.1\5.14.1\msvc2017_64\bin\qmake.exe -o Makefile F:\qthttpserver\src\sslserver\sslserver.pro ) && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\nmake.exe" -f Makefile

Microsoft (R) Program Maintenance Utility Version 14.16.27035.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\nmake.exe" -f Makefile.Release all

Microsoft (R) Program Maintenance Utility Version 14.16.27035.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        rc /NOLOGO -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_LINKED_LIST -DNDEBUG -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_SSLSERVER_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -D_WINDLL -fo .obj\release\Qt5SslServer_resource.res Qt5SslServer_resource.rc
'rc' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: 'rc' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
`

**Comment by TheWanderingCoel** [comment]
``C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat x86`` init your environment first

**Comment by MingqianYang** [comment]
![image](https://user-images.githubusercontent.com/15353430/75637488-db1b8200-5c7a-11ea-9165-de95c43bf993.png)

What do you mean **init your environment?**. Just double click it to init?

And I do not understand the 

**vcvarsall.bat x86**

 mean. There is no **"vcvarsall.bat x86"** in the above folder.

**Comment by TheWanderingCoel** [comment]
run it in command line，x86means x86environment.

**Comment by coderstory** [comment]
run vcvarsall.bat
