### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by bnwproxy** [Trojan-Qt5/Trojan-Qt5#139]
Have errors like this in the trojan log
```
[2020-03-01 19:46:23] [ERROR] 127.0.0.1:38632 SSL handshake failed with xxxx:443: certificate verify failed
[2020-03-01 19:46:23] [INFO] 127.0.0.1:38632 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-03-01 19:46:23] [ERROR] 127.0.0.1:38636 SSL handshake failed with xxxx:443: certificate verify failed
[2020-03-01 19:46:23] [INFO] 127.0.0.1:38636 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-03-01 19:46:27] [WARN] trojan service stopped
```

Yet the certificate is applied using Let's Encrypt and I verified that it is signed... Trojan server's version is 1.14.1, and https://github.com/bnwproxy/bnwproxy-trojan/blob/master/trojan_centos7.sh is used to create the server.

**Comment by TheWanderingCoel** [comment]
Just disable verify Certificate in Profile Editor. It might be due to your operating system's certificate.

**Comment by bnwproxy** [comment]
![image](https://user-images.githubusercontent.com/58411933/75637924-681cf780-5bf7-11ea-9bc7-b6e79fc897e0.png) Wow that was a fast reply. 
As shown in the screenshot, the domain checks out.

**Comment by TheWanderingCoel** [comment]
you can try using cli client for confirmation. If it is trojan qt5’s issue. Please let me know

**Comment by bnwproxy** [comment]
So the cli client works without the verification error. As shown below:

![image](https://user-images.githubusercontent.com/58411933/75638314-3ad14900-5bf9-11ea-9013-864b190c6928.png)

**Comment by bnwproxy** [comment]
By the way, I really appreciate your work. Thank you so much.

**Comment by TheWanderingCoel** [comment]
...awkward. I didn’t do anything to the Trojan core code. I don’t know why... need help for that.

**Comment by bnwproxy** [comment]
Perhaps you could give me an email that I could send the `config.json` to help you debug?

**Comment by TheWanderingCoel** [comment]
You're more than welcome.

**Comment by bnwproxy** [comment]
In addition, the trojan core codebase that you are using, are they of version 1.14.1?

**Comment by TheWanderingCoel** [comment]
yes. 1.14.1

**Comment by TheWanderingCoel** [comment]
I also face this issue in deepin, might be owing to appImage?

**Comment by bnwproxy** [comment]
Hmm, that would be strange, if you have windows by any chance, could you test it out to eliminate the possibility of appImage being the culprit?

**Comment by TheWanderingCoel** [comment]
Which operating system did you have this issue?

**Comment by bnwproxy** [comment]
Arch Linux
![image](https://user-images.githubusercontent.com/58411933/75638674-170f0280-5bfb-11ea-94d1-15d4360c695a.png)

**Comment by TheWanderingCoel** [comment]
Manjaro, Got it.

**Comment by bnwproxy** [comment]
Also just so you know, I am using V0.0.4a https://github.com/TheWanderingCoel/Trojan-Qt5/releases/download/v0.0.4a/Trojan-Qt5-Linux.AppImage

**Comment by TheWanderingCoel** [comment]
I see. Thank you
