### ISSUE TITLE
V0.04 Linux UI图标是韩文

### ISSUE THREAD

**Issue by Kemo-Huang** [Trojan-Qt5/Trojan-Qt5#141]
AppImage的选项图标是韩文，鼠标悬停在韩文上可以正常显示英文。

Operating System: Ubuntu 18.04
Version: v0.04, released on Feb.29

![Screenshot from 2020-03-02 12-58-37](https://user-images.githubusercontent.com/37008277/75646812-d01a1f00-5c85-11ea-8663-2bd54805b62a.png)

**Comment by TheWanderingCoel** [comment]
奇怪...试试004a

**Comment by Rtvpul** [comment]
我没有在设置或者配置文件找到如何调整UI语言的地方，请问能分享一下吗？

**Comment by TheWanderingCoel** [comment]
不能更改语言。语言自动跟随系统语言设置

**Comment by Kemo-Huang** [comment]
回复晚了，这个不是语言的问题，应该是UI显示不正确，类似于像“锟斤拷”这样的乱码。我ubuntu18.04的系统语言是英语，跟这个可能没关系。

**Comment by Kemo-Huang** [comment]
我的问题应该是：本来应该是图标的，却变成了文字，文字是韩文而已

**Comment by TheWanderingCoel** [comment]
我回复的是楼上，你这个问题我可能要点时间研究下。最近都没啥空

**Comment by TheWanderingCoel** [comment]
有点像Font Awesome的问题，我下一个Ubuntu试试

**Comment by TheWanderingCoel** [comment]
![QQ20200314-184811](https://user-images.githubusercontent.com/39617891/76680551-5f2f1b80-6624-11ea-93c0-e885455010b7.png)
经测试，004b没有此问题@Kemo-Huang
