### ISSUE TITLE
能否加入类似ssr客户端pac 与 v2rayn客户端的路由规则的功能呢

### ISSUE THREAD

**Issue by zoeysama** [Trojan-Qt5/Trojan-Qt5#168]
现在0.0.4a版本的pac模式实际上是之前使用ssr客户端的gfwlist模式  即访问gfwlist列表中的域名时则使用代理
有些境外网站虽然没有被gfw墙掉但是我也希望能通过代理进行加速访问
另外使用IDM下载有些网站的文件的时候会无法正常下载

<img width="292" alt="Screenshot - 2020-03-04 20 54 29" src="https://user-images.githubusercontent.com/42513394/75881915-0a88e500-5e5b-11ea-8746-336159b918ab.png">
如上图所示 能否加入类似ssr客户端的pac模式呢  即pac列表中的域名不使用代理（例如图片中的taobao）  而其他情况一概使用代理

另外

<img width="498" alt="Screenshot - 2020-03-04 20 55 07" src="https://user-images.githubusercontent.com/42513394/75882092-6b182200-5e5b-11ea-9fd6-52970e83e772.png">
是否可以如上图所示 加入类似v2rayN客户端的自定路由规则功能呢  

谢谢作者

**Comment by TheWanderingCoel** [comment]
有时间研究加入

**Comment by Itzamana** [comment]
v2rayN
+
https://github.com/Loyalsoldier/v2ray-rules-dat

个人感觉体验很棒！

**Comment by TheWanderingCoel** [comment]
我看下，感觉是v2ray开放的接口，如果在gui层面做的话，我应该可以做到

**Comment by zoeysama** [comment]
送给各位小伙伴一个国内域名规则  适用于新版的pac模式
国内域名(共计70366个  原proxy.pac仅有2000余个) 已经去重并整理为proxy.pac格式
如下图所示
![image](https://user-images.githubusercontent.com/42513394/76682109-2303b700-6634-11ea-9f83-726c27f8a5ec.png)

[domins2.txt](https://github.com/TheWanderingCoel/Trojan-Qt5/files/4332715/domins2.txt)
可以下载domins2.txt  打开文件并自行按需添加到trojan-qt根目录下pac文件夹里的proxy.pac文件中

[proxy.txt](https://github.com/TheWanderingCoel/Trojan-Qt5/files/4332721/proxy.txt)
也可以直接下载proxy.txt  将扩展名修改为pac(即文件名为proxy.pac)放在trojan-qt根目录下pac文件夹中

**Comment by TheWanderingCoel** [comment]
> 送给各位小伙伴一个国内域名规则 适用于新版的pac模式
> 国内域名(共计70366个 原proxy.pac仅有2000余个) 已经去重并整理为proxy.pac格式
> 如下图所示
> ![image](https://user-images.githubusercontent.com/42513394/76682109-2303b700-6634-11ea-9f83-726c27f8a5ec.png)
> 
> [domins2.txt](https://github.com/TheWanderingCoel/Trojan-Qt5/files/4332715/domins2.txt)
> 可以下载domins2.txt 打开文件并自行按需添加到trojan-qt根目录下pac文件夹里的proxy.pac文件中
> 
> [proxy.txt](https://github.com/TheWanderingCoel/Trojan-Qt5/files/4332721/proxy.txt)
> 也可以直接下载proxy.txt 将扩展名修改为pac(即文件名为proxy.pac)放在trojan-qt根目录下pac文件夹中

十分感谢大佬~下一个版本将内置你的规则

**Comment by TheWanderingCoel** [comment]
如果不介意的话，会注明大佬你的名字。（不知是否愿意呢？）
弱弱说一句,domins2.txt和proxy.txt这两个有区别吗？

**Comment by zoeysama** [comment]
> 如果不介意的话 那我内置了，会注明大佬你的名字。（不知是否愿意呢？）
> 弱弱说一句,domins2.txt和proxy.txt这两个有区别吗？

尽管内置便是   还得感谢作者提供了这么好用的GUI客户端  

然后domin2.txt里只有70366行域名  需要自行打开trojan-qt5根目录下pac文件夹中的proxy.pac文件 
 再把domin2.txt里的域名按需要复制到proxt.pac文件中的`var white_domains = `里

proxy.txt是已经添加好域名的规则文件  直接下载下来  修改文件名为proxy.pac   放进trojan-qt5根目录下pac文件夹中就可以用了( Issues中上传附件不能上传扩展名为pac的文件 所以只能先把后缀改成.txt上传  需要下载之后再改回proxy.pac)

再然后就是刚才上传的proxy.txt有点问题  少了一个逗号(手动捂脸)
这个是新的(但愿这个里面没什么别的问题)
[proxy.txt](https://github.com/TheWanderingCoel/Trojan-Qt5/files/4332823/proxy.txt)

**Comment by TheWanderingCoel** [comment]
感谢支持~。感谢规则，有空时添加~

**Comment by TheWanderingCoel** [comment]
Done
