### ISSUE TITLE
Compile TQLibraries Error

### ISSUE THREAD

**Issue by MingqianYang** [Trojan-Qt5/Trojan-Qt5#169]
There is a problem that I cannot solve when compiling **TQLibraries** .

![image](https://user-images.githubusercontent.com/15353430/75948328-50938680-5ef7-11ea-9087-484eafe99cee.png)

I found that **TQLibraries** is not a **QT** project, why use the **`qmak ..`** command?

I assume the  **TQLibraries** should be put into the repository of **Trojan-Qt5** as shown in the following folder, is that correct? If not, how to compile it?
![image](https://user-images.githubusercontent.com/15353430/75948737-52117e80-5ef8-11ea-9540-1444b10b3fff.png)

**Comment by TheWanderingCoel** [comment]
You can't and shouldn't compile TQLibraries, it's binary libraries and header files only. You should copy TQLibraries it to C:\

**Comment by MingqianYang** [comment]
OK, Thanks for your reply.

But here is a question again.  Cannot find the file **plog/log.h**. Do you know why?

![image](https://user-images.githubusercontent.com/15353430/76044572-e2aa9600-5fae-11ea-98a7-7f4b71b4c766.png)

**Comment by TheWanderingCoel** [comment]
``git submodule update --init``
