### ISSUE TITLE
无法使用，使用trojan-qt5  和 shadowsocks  都无法链接购买的节点

### ISSUE THREAD

**Issue by pengzhaowen** [Trojan-Qt5/Trojan-Qt5#203]
无法使用，使用trojan-qt5  和 shadowsocks  都无法链接购买的节点

**Comment by TheWanderingCoel** [comment]
1. 我不和任何服务提供商有任何合作关系。
2.请提供你的日志，怎么个无法使用？
3.请先看wiki
4.请按照模板提交issue

**Comment by majiashu** [comment]
trojan-qt5  mac无法使用

**Comment by TheWanderingCoel** [comment]
> trojan-qt5 mac无法使用

具体表现？请提供日志

**Comment by majiashu** [comment]
你好，我已经解决了，是服务端的问题，谢谢了



在 2020-03-17 19:52:39，"TheWanderingCoel" <notifications@github.com> 写道：

trojan-qt5 mac无法使用

具体表现？请提供日志

**Comment by Coding-Yuan** [comment]
我的也是端口被占用了，不看日志不知道，希望作者能在界面上提示一下

**Comment by TheWanderingCoel** [comment]
@Coding-Yuan 0.0.5加入~
