### ISSUE TITLE
[BUG]编辑user rule的对话框缩放无效

### ISSUE THREAD

**Issue by Atom2004** [Trojan-Qt5/Trojan-Qt5#211]
![image](https://user-images.githubusercontent.com/22042246/77036429-1c858e80-69ea-11ea-9bd1-876aa2f47be4.png)

如图，编辑user-rule的对话框太小了，但是吧窗体放大，实际文本框没有跟随这变大。

**Comment by TheWanderingCoel** [comment]
确实有这个问题，ui的我可能修复有点慢，抱歉

**Comment by TheWanderingCoel** [comment]
Fixed
