### ISSUE TITLE
[BUG] 1.05 升级之后，原有服务器信息错乱

### ISSUE THREAD

**Issue by Akagilnc** [Trojan-Qt5/Trojan-Qt5#227]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of Trojan-Qt5, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, or I fail to look wiki before I submit this issue, my issue will be closed immediately without any notice.
yes
**Trojan-Qt5 Version**
The version of trojan you are using.
1.05
**Describe the bug**
profilename 被填写到了 server address, 导致1.04原有服务器信息全部失效。同时还包括verify certificate 等

**Environment**
What is your operating system? Specific desktop Environment and distribution when you are using Linux.
Mac OS 10.15.3

**Additional context**

**Comment by TheWanderingCoel** [comment]
@Akagilnc 新版修改了配置文件，需要删除配置文件config.ini重新导入服务器信息

**Comment by coderstory** [comment]
10几个节点。。。。搞了好多次了

**Comment by TheWanderingCoel** [comment]
> 10几个节点。。。。搞了好多次了

抱歉，下次更新日志写好需要删除配置文件

**Comment by TheWanderingCoel** [comment]
expected behavior, not a bug
