### ISSUE TITLE
[BUG]mac 10.15.3  原生菜单不能显示

### ISSUE THREAD

**Issue by qyzxg** [Trojan-Qt5/Trojan-Qt5#231]
mac 10.15.3  原生菜单不能显示

**Comment by TheWanderingCoel** [comment]
@qyzxg 勾选后重启软件即可

**Comment by qyzxg** [comment]
试过了

**Comment by TheWanderingCoel** [comment]
@qyzxg 在我这可以显示的，可否截图？

**Comment by qyzxg** [comment]
![image](https://user-images.githubusercontent.com/23406731/77537227-ad6fd480-6ed8-11ea-8cd9-21f606e34c11.png)
设置完后已重启软件
![image](https://user-images.githubusercontent.com/23406731/77537304-cc6e6680-6ed8-11ea-91e1-f6c352f93b87.png)

**Comment by TheWanderingCoel** [comment]
@qyzxg

**Comment by qyzxg** [comment]
TrojanQt5 的原生菜单会闪一下然后就消失了

**Comment by TheWanderingCoel** [comment]
麻烦加一下tg群?

**Comment by qyzxg** [comment]
我在群里

**Comment by TheWanderingCoel** [comment]
直接tg找我就行了

**Comment by TheWanderingCoel** [comment]
已复现，隐藏图标会导致原生菜单栏不存在，只能折中不使用原生菜单栏

**Comment by qyzxg** [comment]
好的 并不影响使用 只是在Mac上习惯使用原生菜单而已，辛苦了，我tg还不能发信息，已经申请解除限制了，谢谢你

**Comment by TheWanderingCoel** [comment]
@qyzxg 没事

**Comment by TheWanderingCoel** [comment]
已解决
