### ISSUE TITLE
[BUG] 上一个版本开始就没有显示菜单

### ISSUE THREAD

**Issue by jdleung** [Trojan-Qt5/Trojan-Qt5#248]
![2020-03-29 ](https://user-images.githubusercontent.com/486474/77845352-d4801c00-71e0-11ea-8641-ad4d6f74c236.png)
MacOS 10.14.5

上一个版本0.05开始，菜单就消失了。原以为0.06会修复，但发现还未解决，刚试了一下在窗口中右击隐藏图标，现在连图标也没有了，右击后的选项也不显示。麻烦修复一下，谢谢

**Comment by TheWanderingCoel** [comment]
@jdleung Command + , 打开常规设置

**Comment by jdleung** [comment]
重启可以了。

另外，目前双击配置是进入编辑，使用中需要编辑应该不多吧？使用习惯上，如果能双击连接会更方便。

谢谢

**Comment by TheWanderingCoel** [comment]
收到

**Comment by likanzhan** [comment]
重启电脑还是程序呢？我这边出现了同样的问题。

**Comment by TheWanderingCoel** [comment]
@likanzhan 程序

**Comment by likanzhan** [comment]
@TheWanderingCoel 
我重启了电脑和程序，还是无法显示，MacOS 10.14.6，软件版本 0.06。

**Comment by TheWanderingCoel** [comment]
@likanzhan 请将设置中的使用原生关闭！！！按command + ，调出设置

**Comment by likanzhan** [comment]
@TheWanderingCoel 试过了，无法调出设置哈。

**Comment by TheWanderingCoel** [comment]
@likanzhan 。。。

**Comment by jdleung** [comment]
> @TheWanderingCoel 试过了，无法调出设置哈。

试一下 "command" + "逗号"，我第一次看使用了 "command" + "+号"

**Comment by likanzhan** [comment]
@jdleung @TheWanderingCoel 

 "command" + "逗号" 是可以的，谢谢。

**Comment by winecat** [comment]
![image](https://user-images.githubusercontent.com/10415943/78044286-08a53980-73a7-11ea-954e-81646d4f1bfa.png)
同样的，"command" + "逗号"  还是不能调出设置，整个窗口只剩下链接列表，没其他了，最大化之后出现系统菜单栏，但是点击无效。 求助，如何调出菜单栏

**Comment by TheWanderingCoel** [comment]
@winecat 建议直接编辑配置文件

**Comment by TheWanderingCoel** [comment]
@winecat [General]
AutoSetSystemProxy=global
CheckPortAvailability=true
ConfigVersion=2.6
EnableHttpMode=false
EnablePACMode=true
HideDockIcon=false
HideWindowOnStartup=false
HttpLocalAddress=127.0.0.1
HttpLocalPort=1081
LogLevel=1
MainTableGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x1\0\0\0\x1\0\0\x3\\\0\0\0\x17\0\0\0\0\0\0\0\0\xff\xff\xff\xff\xff\xff\xff\xff\0\0\0\0\0\0\0\0\x5\xa0\0\0\0\x1\0\0\0\x1\0\0\x3\\\0\0\0\x17)
MainTableState=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x2\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3`\0\0\0\b\0\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x84\0\0\0\0\0\0\0\b\0$
MainWindowGeometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1=\0\0\0\x99\0\0\x4\xb0\0\0\x2\xe0\0\0\x1=\0\0\0\xaf\0\0\x4\xb0\0\0\x2\xe0\0\0\0\0\0\0\0\0\x5\xa0\0\0\x1=\0\0\0\xaf\0\0\x4\xb0\0\0\x2\xe0)"
MainWindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x3t\0\0\x1\xae\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\xe\0t\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xf$
NativeMenuBar=false
OnlyOneInstance=true
PACLocalAddress=127.0.0.1
PACLocalPort=8070
ShowFilterBar=true
ShowToolbar=true
Socks5LocalAddress=127.0.0.1
Socks5LocalPort=1080
StartAtLogin=false
SystemProxyMode=global
ToolbarStyle=3

**Comment by winecat** [comment]
@TheWanderingCoel 没找到配置文件，不然早就把它重置了ORZ

**Comment by TheWanderingCoel** [comment]
~/.config/trojan-qt5/config.ini

**Comment by winecat** [comment]
@TheWanderingCoel get,谢谢
