### ISSUE TITLE
[Feature Request] Forward proxy option

### ISSUE THREAD

**Issue by atwayne** [Trojan-Qt5/Trojan-Qt5#250]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**
The Trojan application doesn't provide an option to set forward proxy. Hence it's difficult to set up this behind a firewall.

**Describe the solution you'd like**
Option 1: A forward proxy dialog like the ShadowSocks Windows client
Option 2: Load proxy settings from environment variables such as "HTTP_PROXY", "HTTPS_PROXY" etc

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TheWanderingCoel** [comment]
@atwayne If trojan does not provide this feature, trojan-qt5 will be hard or even impossible to achieve it. Mark as enhancement for now

**Comment by TheWanderingCoel** [comment]
Done
