### ISSUE TITLE
图标适配各系统风格

### ISSUE THREAD

**Issue by zhiwsun** [Trojan-Qt5/Trojan-Qt5#261]
现在的图标无论在Windows上还是Mac上，都是统一的圆形黄底小木马；这个风格的图标和系统的主流设计风格不是很搭配。尤其是Win10上的工具栏，Mac上的菜单栏部分，感觉有点突兀。是否可以考虑在不同的平台采用和系统风格更搭配的图标。

**Comment by TheWanderingCoel** [comment]
Finished
