### ISSUE TITLE
[Feature Request]您好，关于订阅系统。

### ISSUE THREAD

**Issue by sindy0608** [Trojan-Qt5/Trojan-Qt5#269]
- [x] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below or I don't check this box, my issue will be closed immediately without any notice.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

作者您好，非常感谢您提供这么好用的客户端，请问下trojan连接/订阅 下 能否适配sni验证值呢，比如

trojan://password@domain:port?allowinsecure=value&tfo=value#Optional_Base64(remarks)

增加一个sni的值

trojan://password@domain:port?allowinsecure=value&tfo=value&sni=baidu.com#Optional_Base64(remarks)

感谢您

**Comment by TheWanderingCoel** [comment]
@sindy0608 目前trojan并没有统一的uri规则,allowinsecure=1即可关闭验证证书不需要填写sni

**Comment by sindy0608** [comment]
> @sindy0608 目前trojan并没有统一的uri规则,allowinsecure=1即可关闭验证证书不需要填写sni

感谢回复，因为sni不验证的话容易被钓鱼/安全性问题，目前shadowrocket是支持 peer = xx  这个值来填写sni， surge 与 quanX等软件也都有对应的值。所以还是希望能折中适配一下

再次感谢

**Comment by TheWanderingCoel** [comment]
还是得遵循trojan官方uri,不然会导致很多机场订阅全部失效。目前@?&:#都用作分隔符了,再用一次&也会出点问题

**Comment by TheWanderingCoel** [comment]
Done
