### ISSUE TITLE
[BUG]右键菜单栏里的服务器选相，若节点太多，最后面无法看到

### ISSUE THREAD

**Issue by smilelandchr** [Trojan-Qt5/Trojan-Qt5#273]
- [ ] I certify that I have read the contributing guidelines and I acknowledge if I don't follow the format below, or I'm using an old version of Trojan-Qt5, or I apparently fail to provide sufficient information (such as logs, specific numbers), or I don't check this box, or I fail to look wiki before I submit this issue, my issue will be closed immediately without any notice.

**Trojan-Qt5 Version**
0.0.8

**Describe the bug**
[BUG]右键菜单栏里的服务器选相，若节点太多，最后面无法看到。
[![](https://i.loli.net/2020/04/06/I98DLlAUwxHukPc.png)](url)
同时，知道这个功能本意是希望能够快速选择节点，但是像我这样满屏的节点覆盖，我想去点击“系统代理模式”便很不方便操作，因为在路过服务器选相时便弹出了满屏的节点目录。
**To Reproduce**

**Expected behavior**
希望删除这个功能，双击调出主界面选择节点就挺方便的，并不会比右键选择多操作步骤。或者将这个选相调整位置，至少个人觉得操作PAC模式是更高频的操作。

**GUI Log**
If applicable, add GUI Log to help explain your problem.

**Trojan Log**
If applicable, add Trojan log to help explain your problem

**Environment**
win7

**Additional context**

**Comment by TheWanderingCoel** [comment]
已添加设置，可控制数量
