### ISSUE TITLE
[Feature Request] 期望系统代理模式默认为PAC模式

### ISSUE THREAD

**Issue by Leskur** [Trojan-Qt5/Trojan-Qt5#275]
**产生问题原因：**

在给某初级用户安利的时候，他们会搞不懂代理模式的区别是什么，或者不知道如何确认配置是否正确。

**导致的问题：**
1. 在配置错误的情况下设置了全局模式会导致无法正常浏览所有网页

1. 配置正确的情况下，全局代理的会对访问国内资源造成一定影响，他们并不知道如何去解决。
如果默认设置为PAC-GFWList模式，即可比较合理有效的避免这些问题，减少沟通成本。

**Comment by TheWanderingCoel** [comment]
@Leskur 下个版本加入

**Comment by Leskur** [comment]
😁 👍

**Comment by TheWanderingCoel** [comment]
Done
