### ISSUE TITLE
[BUG]关闭二级窗口会退出程序

### ISSUE THREAD

**Issue by guoPengSong** [Trojan-Qt5/Trojan-Qt5#277]
**Trojan-Qt5 Version**
trojan MAC版，版本号：0.0.8

**Describe the bug**
打开订阅设置的二级窗口，或者手动添加服务器的二级窗口，点击二级窗口的关闭按钮，trajon会退出

**To Reproduce**

**Environment**
MAC版本号：10.14.5

**Comment by TheWanderingCoel** [comment]
@guoPengSong 10.15.3 没有这个问题

**Comment by liupeng3425** [comment]
10.15.4 新增服务器订阅窗口，点击确定会导致程序退出。

**Comment by TheWanderingCoel** [comment]
怀疑是不是10.15.4的bug，我这里10.15.3没有问题

**Comment by guoPengSong** [comment]
> 怀疑是不是10.15.4的bug，我这里10.15.3没有问题

是得先关闭trojan主窗口，点击右上角的trojan图标去进行订阅什么的操作，才能复现，不关闭主窗口复现不了，我这里是这么个情况

**Comment by TheWanderingCoel** [comment]
> > 怀疑是不是10.15.4的bug，我这里10.15.3没有问题
> 
> 是得先关闭trojan主窗口，点击右上角的trojan图标去进行订阅什么的操作，才能复现，不关闭主窗口复现不了，我这里是这么个情况

复现了，我去看下

**Comment by liupeng3425** [comment]
> > > 怀疑是不是10.15.4的bug，我这里10.15.3没有问题
> > 
> > 
> > 是得先关闭trojan主窗口，点击右上角的trojan图标去进行订阅什么的操作，才能复现，不关闭主窗口复现不了，我这里是这么个情况
> 
> 复现了，我去看下

这回复速度赞！确实和@guoPengSong 说的一样，关闭主窗口才可以复现。

**Comment by TheWanderingCoel** [comment]
@liupeng3425 测试了下，pac规则也是，暂时不清楚什么问题

**Comment by liupeng3425** [comment]
> @liupeng3425 测试了下，pac规则也是，暂时不清楚什么问题

可能是检查到没有窗口就退出了？不是很懂QT，可以搜索一下。

**Comment by TheWanderingCoel** [comment]
错误已定位，刚看到消息，的确设置了这个就没问题了。
我看的这个链接[link](https://stackoverflow.com/questions/46143546/application-closes-when-its-hidden-and-i-close-a-modal-dialog)

**Comment by TheWanderingCoel** [comment]
Done
