### ISSUE TITLE
[BUG]断开连接后，需要重启客户端才能再次连接

### ISSUE THREAD

**Issue by hhsummerwind** [Trojan-Qt5/Trojan-Qt5#286]
客户端版本：v0.0.8
系统：ubuntu16.04

打开客户端可以正常连接，然后断开节点，想再次连接，没有反应。需要重启客户端后才可再次连接。

**Comment by TheWanderingCoel** [comment]
@hhsummerwind privoxy端口无法释放重新绑定导致问题，需要研究，已确认这个bug

**Comment by TheWanderingCoel** [comment]
Fixed
