### ISSUE TITLE
[Feature Request]Could you please rebuild the 0.0.4c release?

### ISSUE THREAD

**Issue by yangjianhua** [Trojan-Qt5/Trojan-Qt5#288]
The latest version cannot use, too slow.

The 0.0.4c version is the best for me, could you please release that version?

thx.

**Comment by TheWanderingCoel** [comment]
@yangjianhua 0.0.4 version contain serious bugs and won't be released again.

**Comment by TheWanderingCoel** [comment]
the latest version can reach 13w+ in youtube 4k test. What do you mean by too slow?
