### ISSUE TITLE
NB，003版可以打开网页了

### ISSUE THREAD

**Issue by bomersyx** [Trojan-Qt5/Trojan-Qt5#29]
就是感觉还有点不稳定，用段时间看看

**Comment by TheWanderingCoel** [comment]
好的，欢迎随时反馈~现在有日志了，可以方便判断一点

**Comment by Badalin** [comment]
> 好的，欢迎随时反馈~现在有日志了，可以方便判断一点

003在哪下载啊？

**Comment by TheWanderingCoel** [comment]
> > 好的，欢迎随时反馈~现在有日志了，可以方便判断一点
> 
> 003在哪下载啊？

在releases里

**Comment by left3721** [comment]
在等 Linux版本啊

**Comment by TheWanderingCoel** [comment]
> 在等 Linux版本啊

linux构建有点慢，因为都是从源码构建的。稍等几分钟

**Comment by TheWanderingCoel** [comment]
> 在等 Linux版本啊

Linux翻车了，对不起，稍等

**Comment by avalond** [comment]
mac 版本还在构建吗？

**Comment by TheWanderingCoel** [comment]
> mac 版本还在构建吗？

因为Linux的问题，我把所有releases删了，实在对不起，只能等travis-ci构建完

**Comment by TheWanderingCoel** [comment]
> mac 版本还在构建吗？

刷新下releases，应该有了

**Comment by left3721** [comment]
OK了可以 打开网页了 
Log 里报certificate verify failed 关掉证书验证就正常了
断开连接再连偶尔会闪退下

**Comment by TheWanderingCoel** [comment]
是自签的证书吗？自签的貌似会错误，推荐lets encrypt

**Comment by TheWanderingCoel** [comment]
闪退的话麻烦开一个issue，我研究下

**Comment by Caihonghua** [comment]
003版本，连不上。软件貌似没遇到什么问题，但是就是连不上。能ping通IP但是代理不了，应该不是软件问题吧?

**Comment by robin20200222** [comment]
我一直都下载不下来，有那个大神分享我一下。

**Comment by robin20200222** [comment]
> 就是感觉还有点不稳定，用段时间看看

可以分享一下软件吗？我还一直都下载不了

**Comment by TheWanderingCoel** [comment]
> 003版本，连不上。软件貌似没遇到什么问题，但是就是连不上。能ping通IP但是代理不了，应该不是软件问题吧?

可以发一下日志，顺便关掉pac模式试试？
