### ISSUE TITLE
如何进行局域网共享？

### ISSUE THREAD

**Issue by toneywu** [Trojan-Qt5/Trojan-Qt5#297]
假设我在一台电脑上（ip:192.168.3.8) 运行了，并在设置中开启了局域网共享。
现在Socks5：51837
Http:58591
PAC：8070
haproxy: 7777
haproxy: 2080

我的另一台平板如何通过这一台192.168.3.8进行共享代理？？WIFI设置时走什么端口？

**Comment by Silh0uettie** [comment]
iPhone上是进到wlan>(你的网络名字后面有个i的小圈圈)>HTTP代理(拉到底就能看到)>手动>ip:192.168.3.8, port: 58591
端口我填socks5的端口也有效，pac的就不行，还有两个没试过。不是很清楚这几个的区别……

如果是iPad的话应该是一样的，安卓就不知道了。windows的话也是找到代理，然后填一样的东西。

PS:我一开始无法分享，找了好久才发现是防火墙的原因……我的ESET开的自动模式就会分享不出去，关掉防火墙或者设置例外就可以了。不过每台电脑都不同，你不一定会碰到这个问题。
