### ISSUE TITLE
1.1.4 在windows上提示需要管理员权限

### ISSUE THREAD

**Issue by luoqiz** [Trojan-Qt5/Trojan-Qt5#318]
1.1.4 在windows上提示需要管理员权限。但是调整后也不行，甚至一启动就直接退出了。先前没有这个情况

**Comment by iheshun** [comment]
在MAC上也有这个问题，具体表现是提示需要ROOT权限，内容如下：

你需要用管理员/root权限启动该程序
查看下面的链接作为参考:
https://zh.wikihow.com/%E5%9C%A8Mac%E7%94%B5%E8%84%91%E4%B8%8A%E4%BD%BF%E7%94%A8Root%E6%9D%83%E9%99%90%E6%89%93%E5%BC%80%E5%BA%94%E

**Comment by TheWanderingCoel** [comment]
@iheshun 不知道什么是增强模式就不要选增强模式

**Comment by iheshun** [comment]
@TheWanderingCoel 
谢谢管理员的提醒，主要是PAC模式已经访问不了Google了，然后就尝试了全局模式（可以访问），但是感觉访问国内网站的速度很受影响，所以才尝试了增强模式，这个确实也是自己的锅。

所以，还是期望管理员看看是不是软件出问题了，PAC模式真的访问不了外网了。

**Comment by TheWanderingCoel** [comment]
PAC的确有点问题，近期会调查，感谢反馈

**Comment by luoqiz** [comment]
我这切换到pac正常了。
