### ISSUE TITLE
Mac更新后无法使用，卸载新版本回退了也无法使用

### ISSUE THREAD

**Issue by GimmGoo** [Trojan-Qt5/Trojan-Qt5#319]
core日志：
![image](https://user-images.githubusercontent.com/31849284/83710906-6af31280-a654-11ea-88f2-786afa8f6d1b.png)
GUI日志：
![image](https://user-images.githubusercontent.com/31849284/83710921-721a2080-a654-11ea-8f30-a7f15605d351.png)

无论使用什么模式，都是显示链接上了，但是无法访问外网。网页显示连接已重置或者XXX意外终止了连接。升级前是可以用的。

**Comment by TheWanderingCoel** [comment]
不知道什么是前置代理就不要开前置代理

**Comment by GimmGoo** [comment]
> 不知道什么是前置代理就不要开前置代理

我就没动什么代理好吗？都是点击连接，软件控制。升级前，用软件直接连接就可以用，都不用额外的设置。你不知道是什么情况就说我不知道什么是前置代理就不要开前置代理？是不是问到你不会的让你难堪了？没能力回答直接说你不懂啦。哪怕软件是你写的，你的回复态度都有问题，虽然说你没有义务回答，或者说我爱用不用。

**Comment by Begin12** [comment]
> > 不知道什么是前置代理就不要开前置代理
> 
> 我就没动什么代理好吗？都是点击连接，软件控制。升级前，用软件直接连接就可以用，都不用额外的设置。你不知道是什么情况就说我不知道什么是前置代理就不要开前置代理？是不是问到你不会的让你难堪了？没能力回答直接说你不懂啦。哪怕软件是你写的，你的回复态度都有问题，虽然说你没有义务回答，或者说我爱用不用。

这态度，ennnnn我觉得你有能力做这个软件，这问题对你来说，处理起来应该是得心应手，你有望成为团队的主心骨，一看就有领导才能。       不禁让我想起了   马说 中的一句话        “其真无马邪？其真不知马也！”         感叹一下      是不大佬

**Comment by GimmGoo** [comment]
听说过赵高吗？指鹿为马那个。其真马邪？顿悟一下？

**Comment by Begin12** [comment]
> 听说过赵高吗？指鹿为马那个。其真马邪？顿悟一下？

没有听过   大佬指点一二

**Comment by GimmGoo** [comment]
不好意思，你这厮不配。

**Comment by Begin12** [comment]
> 不好意思，你这厮不配。

这么说   我还是一种生物    你连生物都不配了

**Comment by kingofotaku** [comment]
@GimmGoo 是是是 您配 您这么厉害怎么连log都没看懂？

**Comment by MarksonHon** [comment]
1086端口是Trojan-Qt5默认的前置代理端口，不过没有一个代理软件会默认启用前置代理罢了。阁下自视甚高，为啥不检查一下自己的设置呢？

**Comment by bluefoxfish** [comment]
> 不知道什么是前置代理就不要开前置代理


> 不好意思，你这厮不配。

我作为一个技术小白！从网页VPN插件，SS/SSR   酸酸乳、v2rayn  到后来开始尝试自己购买VPS虚拟服务器搭建属于自己的网络专线！
遇到过无数难以解释的技术难题，对于不会的问题，我反复在谷歌查询资料，实在不会就会询问电报群里的网友!大家都比较热心！
俗话说，三人行，必有我师！得做到不耻下问！但是我在询问问题的时候，碰到很多开发软件的作者，并没有很好的解答！都是很牛的！
毕竟软件是人家开发的，已经做为开源程序免费供你使用了，就不要那么多事，去问怎么办！做为一个使用安卓系统的技术爱好者，碰到
免费开源的翻墙软件程序，我感到很开心了！因为我很感恩！如果没有这些技术大神，做为一个小白，永远不会知道外边的世界有多么美好！
毕竟开发软件的作者，没有图名图利！很热心的开发！供大家免费下载使用！我真的感到很感恩！在这里我由衷的说一声“谢谢”
但是今天我看到了一个让人感到很恶心的事情！QT5的作者遭到了一个使用者的侮辱！ 我使用QT5 已经很久了！从最初的1.1版本！到现在的
1·5版本，都是非常不错的！使用过程中也遇到了很多这样或那样的问题，QT5的作者，总是很耐心的去解答！但是这个QT5是作者一个人独立
开发完成的，里面或多或少有这样那样的BUG!这在所难免！而且人家根据系统需要开发了适用于各系统的版本！我作为一名免费的使用者，感到很荣幸
遇到了这样的作者！从内心中很感谢QT5作者免费开源的公布程序代码！感谢作者有时在百忙之中为我这个小白，解答技术问题！
但是人得有自知之明!我今天看到你给作者的留言！我作为一个使用QT5的小白必须说：你作为一个“成年人”在作者群里发出那样的言论，你连一个小孩子都不如！从你给软件作者发出的信息来看，你真是一个极度自私的人！或者说心理阴暗，变态的人！！！你不懂得感恩！！！！你没有生活工作的能力吗？ 难道说，你吃饭的时候，还要旁边有一个专门为你服务的佣人？而这个佣人没有拿到你的任何酬劳，还要让你来侮辱？？？
你免费使用人家用珍贵精力和时间开发出的软件，这头确恬不知耻的骂着软件开发者！
你知道“人”字是怎么写的吗？你的思想里根本就没有学会“尊重”根本就没有学会感恩！我在想，这次全世界爆发新冠病毒疫情！你怎么没有被感染！看来，有时候老天爷也有打盹的时候，没有把你给收了！你让我感到，你是一个及其心理阴暗的变态的“人”从小到大，学校一直教 思想品德课！你的父母是怎么培养你的呢？？？？缺乏道德感！极度自恋！ 心理阴暗，不知道感恩！而且做为一个从旁观角度看：你简直就是长着人的皮囊，确没有干人事的牲口！
