### ISSUE TITLE
shadowsocks 客户中心网页无法登陆

### ISSUE THREAD

**Issue by BarretYoung** [Trojan-Qt5/Trojan-Qt5#321]
shadow socks 客户中心网页是更新了吗？

**Comment by TheWanderingCoel** [comment]
@BarretYoung ？？？

**Comment by DuckSoft** [comment]
？？？

**Comment by Qv2ray-dev** [comment]
@BarretYoung ???

**Comment by studentmain** [comment]
这里是 shadowsocks windows 客户端开发组的 studentmain ，我们不出售任何东西也并没有客户中心，我们的官网只有一个，是 https://shadowsocks.org/ ，其他网站都是仿冒。如果你是在第三方购买的服务，请你与他们联系。
