### ISSUE TITLE
[Advice] Upload to AUR

### ISSUE THREAD

**Issue by github-young** [Trojan-Qt5/Trojan-Qt5#323]
(It is not an issue about bugs.)

I am thinking if you could upload the arch tar.xz package to the AUR? The only package in AUR now is out-dated: [trojan-qt5-appimage 1.0.4-1](https://aur.archlinux.org/packages/trojan-qt5-appimage/).

Or if you don't want to do it yourself, can I upload it to AUR, if possible?

Thank you.

**Comment by DuckSoft** [comment]
@github-young I will make the package then.

**Comment by github-young** [comment]
@DuckSoft  Thank you.

**Comment by DuckSoft** [comment]
@github-young Done
