### ISSUE TITLE
Will free trojan server  steal my privacy?免费trojan账号会盗取隐私吗？

### ISSUE THREAD

**Issue by bit-rocket** [Trojan-Qt5/Trojan-Qt5#324]
I found here http://www.trojanfree.com provides free trojan server, will the provider steal my privacy of what I am browsing? Thanks if anybody knows.
我在用一个网站提供的免费trojan账号，他们不会盗取我的隐私知道我访问的内容吧？

**Comment by h31105** [comment]
是的，您的信息对我们来说很宝贵。

**Comment by MarksonHon** [comment]
就技术而言，如果他们想知道你访问啥很容易，只不过他们并不知道你是谁、也很难知道你是谁罢了。毕竟代理软件不是QQ与微信，不需要实名认证。
但是，有条件要么买机场，要么自建。机场在客户端内部的“关于”项里面有推荐。
