### ISSUE TITLE
snell协议电脑端无法正常使用

### ISSUE THREAD

**Issue by sad-castle** [Trojan-Qt5/Trojan-Qt5#335]
反馈一个问题，通过一键脚本部署了snell协议，手机端通过小火箭可以正常使用，电脑端用QT5死活都不行，混淆用的tls。同一台电脑用Trojan就没问题，换Snell不行，但是小火箭跟qt5客户端配置完全一样的情况下qt5又不行，查不到问题在哪了，是我哪里配置不正确吗![image](https://s1.ax1x.com/2020/06/09/tIDgiQ.jpg?raw=true)

**Comment by TheWanderingCoel** [comment]
@sad-castle snell没写完

**Comment by TheWanderingCoel** [comment]
已完成。
