### ISSUE TITLE
使用后无法pull || push至github

### ISSUE THREAD

**Issue by kalfbz** [Trojan-Qt5/Trojan-Qt5#336]
git提示错误Failed to connect to github.com port 443 Operation timed out，请问是需要设置哪里吗？

**Comment by TheWanderingCoel** [comment]
@kalfbz 跟软件没关系，自己手动设置命令行代理。windows将export换成set

**Comment by kalfbz** [comment]
> @kalfbz 跟软件没关系，自己手动设置命令行代理。windows将export换成set

我是Mac，您的意思是git config --global https.proxy https://”软件PAC地址” ？

**Comment by TheWanderingCoel** [comment]
@kalfbz 请使用软件复制代理命令，pac不是这么用的！

**Comment by kalfbz** [comment]
> @kalfbz 请使用软件复制代理命令，pac不是这么用的！

谢谢，我将git的http代理到127.0.0.1:58591，https代理到localhost:1080成功解决问题。但始终不明白git当中的https与http的代理需要以软件中的SOCKS5、HTTP、PAC哪个为准，他们三个的端口分别是51837、58591、8070。

**Comment by TheWanderingCoel** [comment]
@kalfbz https, http全部指向58591

**Comment by kalfbz** [comment]
> @kalfbz https, http全部指向58591



> @kalfbz https, http全部指向58591

感谢！
