### ISSUE TITLE
Deb package 依赖版本

### ISSUE THREAD

**Issue by madjxatw** [Trojan-Qt5/Trojan-Qt5#340]
Debian 10 的 libuv1 还是 1.24 版本

>Depends: libuv1 (>= 1.34.2-1~) but 1.24.1-1 is to be installed

能否降低该依赖的版本，否则只能使用 AppImage了。

**Comment by TheWanderingCoel** [comment]
@madjxatw 因为ssr核心需要，无法降低，不过你可以开启buster-backports手动下载源码包编译libuv1

**Comment by madjxatw** [comment]
> @madjxatw 因为ssr核心需要，无法降低，不过你可以开启buster-backports手动下载源码包编译libuv1

libuv1 尚未 backport 到 buster。

**Comment by TheWanderingCoel** [comment]
@madjxatw /etc/apt/sources.list中添加deb http://mirrors.aliyun.com/debian buster-backports main
apt-get update更新然后
apt-get source libuv1
cd libuv1
dpkg-buildpackage -us -uc
dpkg -i libuv1xxx.deb
我deepin 20安装也没问题啊，基于debian 10

**Comment by TheWanderingCoel** [comment]
@TheWanderingCoel 以及添加deb-src http://mirrors.aliyun.com/debian unstable main

**Comment by madjxatw** [comment]
如果依赖关系没有问题的话，直接从 unstable 下载 Deb 包就 OK了，跟 backports 没有关系了。

**Comment by TheWanderingCoel** [comment]
@madjxatw 之前打错了，请用src编译安装deb包

**Comment by madjxatw** [comment]
@TheWanderingCoel ，好的，感谢你的回复
