### ISSUE TITLE
Mac客户端连接成功后无法正常上网

### ISSUE THREAD

**Issue by warthur1214** [Trojan-Qt5/Trojan-Qt5#343]
macOS：10.15.5
Trojan-Qt5：1.1.6

GUI日志如下：
>2020-06-15 13:48:18.342 ERROR [API] Trojan API Request failed: 14 (Socket closed)
>2020-06-15 13:49:02.731 ERROR [API] Trojan API Request failed: 14 (failed to connect to all addresses)
>2020-06-15 13:50:38.623 ERROR [API] Trojan API Request failed: 14 (Socket closed)

核心日志如下：
![image](https://user-images.githubusercontent.com/13415982/84622823-842b7700-af10-11ea-84f0-4f2ef3d4dea2.png)

使用Trojan客户端可以正常使用

**Comment by TheWanderingCoel** [comment]
@warthur1214 系统代理没被设置上

**Comment by warthur1214** [comment]
@TheWanderingCoel 谢谢。原来pac代理地址需要手动配置，我看TrojanX可以自动配置

**Comment by TheWanderingCoel** [comment]
@warthur1214 可以自动配置的，你电脑估计出了啥问题？

**Comment by warthur1214** [comment]
@TheWanderingCoel 明白了，非常感谢
