### ISSUE TITLE
V1.2.0，测试所有连接均显示超时，单独测试可成功

### ISSUE THREAD

**Issue by MidnightV1** [Trojan-Qt5/Trojan-Qt5#351]
### 环境

- Trojan-Qt5 版本：V1.2.0
- 操作系统版本：Windows 10

### 操作步骤
菜单中点击测试所有连接延迟，所有节点均为超时。单独对某一结点进行测试没有问题

另外机场用户希望能把测试所有连接延迟的功能往主菜单调整，毕竟现在这个环境下每天都要检查下线路质量

**Comment by TheWanderingCoel** [comment]
@MidnightV1 换到TCP测试方法。。。真延迟测试只是beta

**Comment by MidnightV1** [comment]
> @MidnightV1 换到TCP测试方法。。。真延迟测试只是beta

好了，按说增加选项了不应该放默认设置
