### ISSUE TITLE
mac 上报这个错不是很奇怪？Your config.ini was upgraded from old version of Trojan-Qt5.

### ISSUE THREAD

**Issue by dbeenlee** [Trojan-Qt5/Trojan-Qt5#356]
### 简要描述问题
![image](https://user-images.githubusercontent.com/4352949/85090534-f3a6ac80-b217-11ea-8a0c-04793a76b417.png)

### 环境

- Trojan-Qt5 版本：1.20
- 操作系统版本：macos 10.15.5

**Comment by TheWanderingCoel** [comment]
@dbeenlee 不能覆盖安装，就是为了防止覆盖安装，特意加的

**Comment by KingAmo** [comment]
https://github.com/Trojan-Qt5/Trojan-Qt5/wiki/FAQ wiki上没有相关的说明呢？我卸载重装仍报错

**Comment by xiaoxinda** [comment]
rm   /System/Volumes/Data/Users/$USER/.config/trojan-qt5/config.ini

**Comment by dbeenlee** [comment]
已解决  多谢

**Comment by leonmax** [comment]
其实就是home下面的配置啦
```bash
rm ~/.config/trojan-qt5/config.ini
```

**Comment by wenyutl** [comment]
我看不懂，要删除的文件在哪里，电脑里没有搜索到，能指教一下吗？谢谢你。
