### ISSUE TITLE
VMware虚拟机如何共享宿主机的网络

### ISSUE THREAD

**Issue by wangzk1900** [Trojan-Qt5/Trojan-Qt5#363]
我在本机（windows系统）安装了Trojan-Qt5，并且能够科学上网。
请问，本地创建的VMware虚拟机（centos7）能够共享本机的网络并科学上网吗？
如果能的话该如何配置。

**Comment by eryaozm** [comment]
入站设置开启局域网共享，VMware中设置网络桥接，记下Windows下的IP地址和Trojan-qt5的端口，在centos中设置相应的变量即可

**Comment by wangzk1900** [comment]
多谢！
