### ISSUE TITLE
导出subscribe.txt 订阅错误识别成一个节点

### ISSUE THREAD

**Issue by cddriver** [Trojan-Qt5/Trojan-Qt5#365]
### 简要描述问题
文件菜单下导出subscribe.txt 格式有问题，base64解密后会发现：各trojan节点地址文本内容连在一起，未能分行显示。在trojan-qt5以及shadowrocket下实验，会将subscribe.txt文件中的多个节点地址错误识别成一个节点。
### 环境

- Trojan-Qt5 版本：1.2.0
- 操作系统版本：win以及macOS

### 操作步骤
1.在程序中添加各个trojan节点地址
2.在文件菜单下导出subscribe.txt
3.上传subscribe.txt至文件服务器
4.在trojan-qt5中添加服务器订阅地址。在shadowrocket中添加订阅地址
5.trojan-qt5以及shadowrocket 会将subscribe.txt中的各个节点错误识别成一个节点地址

### 期望的结果
希望能修复

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by TheWanderingCoel** [comment]
commit已修复，下个版本推送
