### ISSUE TITLE
Debian package should specify the lowest version for libgrpc++1

### ISSUE THREAD

**Issue by idnsunset** [Trojan-Qt5/Trojan-Qt5#366]
**Is your feature request related to a problem? Please describe.**

I downloaded the 1.2.0 realese deb file and got it installed using `apt install` locally. However, I got the following error when running trojan-qt5:

>trojan-qt5: symbol lookup error: trojan-qt5: undefined symbol: _ZN9grpc_impl17CreateChannelImplERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt10shared_ptrINS_18ChannelCredentialsEE

This is because I am running Debian 10 stable on my machine and the libgrpc++1 in the repo is of 1.16 version which has no such symbol. I update it to 1.26 from backports and it then works.

**Describe the solution you'd like**

Since stable usually takes precedence over backports  (unless deliberately configured in APT preferences), it would be better to specify the lowest version for libgrpc++1, thus to have APT either pick the correct version from backports (if set up) or report dependency unmet.

**Comment by TheWanderingCoel** [comment]
I use libgrpc9 so you should use backports. If you don't want use libgrpc9, use appimage instead.

**Comment by idnsunset** [comment]
I also use libgrpc9. I enabled the backports and apt install libgrpc9 from backports automatically since libgrpc9 is defined as one of  the dependency.  The problem is libgrpc++1 it self. The version is stable is 1.16 while that in backports is 1.26, APT install the one from stable as stable takes precedence, that's why I suggest you should specify the version for libgrpc++1 so that APT knows which it should choose.

**Comment by TheWanderingCoel** [comment]
@idnsunset I see, will update in the next version

**Comment by idnsunset** [comment]
> @idnsunset I see, will update in the next version

Thanks!
