### ISSUE TITLE
建议默认字体设置为微软雅黑

### ISSUE THREAD

**Issue by rainonline** [Trojan-Qt5/Trojan-Qt5#367]
宋体真是很难看啊

**Comment by rainonline** [comment]
![image](https://user-images.githubusercontent.com/16534596/85246429-31583f00-b47d-11ea-8b8a-c84a69b2b3a1.png)

**Comment by TheWanderingCoel** [comment]
@rainonline 那是样式表掉了，默认是雅黑和Arial，从没设置过

**Comment by rainonline** [comment]
@TheWanderingCoel 1.1.2 版本的样式表没掉，默认也是宋体
![image](https://user-images.githubusercontent.com/16534596/85247233-ac225980-b47f-11ea-9a9c-512dbb55eb31.png)
