### ISSUE TITLE
无法启动，程序报错！

### ISSUE THREAD

**Issue by EndlessJY** [Trojan-Qt5/Trojan-Qt5#368]

**Comment by EndlessJY** [comment]
图片无法上传
报错内容：
Your config.ini was upgraded from old version of Trojan-Qt5.
A clean install is required.
Checkout wiki for instructions
原本旧程序已经卸载干净

**Comment by EndlessJY** [comment]
> _No description provided._

**Comment by TheWanderingCoel** [comment]
rm -rf ~/.config/trojan-qt5

**Comment by EndlessJY** [comment]
> rm -rf〜/ .config / trojan-qt5

谢谢！
