### ISSUE TITLE
使用代理http端口58591无法连接

### ISSUE THREAD

**Issue by tom0gao** [Trojan-Qt5/Trojan-Qt5#369]
### 环境

- Trojan-Qt5 版本：1.1.6
- 操作系统版本：MACOS15.15

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by TheWanderingCoel** [comment]
@tom0gao 描述不清的问题将会被关闭。

**Comment by TheWanderingCoel** [comment]
@tom0gao 请提供日志，表现，截图等
