### ISSUE TITLE
mac pac模式不可用

### ISSUE THREAD

**Issue by zmj1368** [Trojan-Qt5/Trojan-Qt5#374]
### 环境

- Trojan-Qt5 版本： v1.2.0
- 操作系统版本：macos catalina 10.15.5

### 操作步骤
1 修改pac端口为 8050
2 开启pac模式 不可用
3 开启全局模式 可以正常使用

### 期望的结果
1 pac 模式可以正常使用

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by TheWanderingCoel** [comment]
@zmj1368 修改端口要重启软件

**Comment by zmj1368** [comment]
我知道了,也解决了。但这个解决方法我很迷。pac模式一定要更新下pac文件，不更新就不能用，不知道pac模式为什么要这么设置。
