### ISSUE TITLE
如何配合SwitchyOmega使用

### ISSUE THREAD

**Issue by Kegekkk** [Trojan-Qt5/Trojan-Qt5#375]
我想使用SwitchyOmega的autoswitch功能，但是不知道proxy模式该如何配置，希望能告诉我怎样找到正确的代理服务器和端口（127.0.0.1:1080无法正常使用），谢谢

**Comment by TheWanderingCoel** [comment]
@Kegekkk 应用程序最下面不是写了SOCKS5多少多少？哪来的1080
