### ISSUE TITLE
AppImage builds missing

### ISSUE THREAD

**Issue by GoliathLabs** [Trojan-Qt5/Trojan-Qt5#379]
**Is your feature request related to a problem? Please describe.**
You've stopped providing AppImages within the latest releases.

**Describe the solution you'd like**
I'd love to see AppImages coming back to this or further releases.

Cheers,
Felix

**Comment by TheWanderingCoel** [comment]
@GoliathLabs Hi Felix, I'm afraid you misunderstood. AppImage's filename have changed to Trojan-Qt5-Linux.7z. Cheers, TheWanderingCoel.

**Comment by GoliathLabs** [comment]
Okay,
thank you :) It might help to add that to the README so others can find them more easily. Thank you for your quick response :)

Cheers,
Felix
