### ISSUE TITLE
连接后网页无法打开

### ISSUE THREAD

**Issue by Amareyy** [Trojan-Qt5/Trojan-Qt5#38]
如图，就和断网了一样
![无标题12](https://user-images.githubusercontent.com/33324468/75086613-3fe72600-5571-11ea-9bf8-b64e34a72bb5.png)

**Comment by Amareyy** [comment]
![无标题](https://user-images.githubusercontent.com/33324468/75086682-fa772880-5571-11ea-99ec-70e59d1b2653.jpg)

**Comment by TheWanderingCoel** [comment]
尝试关掉PAC模式，PAC有点问题

**Comment by lwmxiaobei** [comment]
> 尝试关掉PAC模式，PAC有点问题

我的也一样，不过我百度可以访问，外网还是不行，关闭了 PAC

**Comment by lwmxiaobei** [comment]
> > 尝试关掉PAC模式，PAC有点问题
> 
> 我的也一样，不过我百度可以访问，外网还是不行，关闭了 PAC

试了好多个节点都不行

**Comment by lwmxiaobei** [comment]
![image](https://user-images.githubusercontent.com/16284775/75132910-af951680-5713-11ea-9893-72eac184cb3f.png)

**Comment by TheWanderingCoel** [comment]
检查一下密码是否正确？post日志看看

**Comment by lwmxiaobei** [comment]
> 检查一下密码是否正确？post日志看看
密码是没错的，节点配置我通过导入文件的，配置信息都是默认的，1080和1081 端口正常开启，但就是访问不了 google.com, trojan.log 只有启动的日志，访问日志也没有
![image](https://user-images.githubusercontent.com/16284775/75141926-f3484a00-572c-11ea-8822-1a74fa958915.png)
这是设置项
![image](https://user-images.githubusercontent.com/16284775/75142002-196dea00-572d-11ea-9125-f999be37fa7b.png)

**Comment by lwmxiaobei** [comment]
会不会是节点问题呢？

**Comment by TheWanderingCoel** [comment]
第一个打勾，是自动设置系统代理的意思。你没打开就不会设置系统代理

**Comment by lwmxiaobei** [comment]
> 第一个打勾，是自动设置系统代理的意思。你没打开就不会设置系统代理

![image](https://user-images.githubusercontent.com/16284775/75223075-a58d1980-57e0-11ea-87c2-5e3ea9b2a212.png)
嗯,勾选了自动设置代理，有请求日志，但是还是打不开 google

**Comment by lwmxiaobei** [comment]
> 第一个打勾，是自动设置系统代理的意思。你没打开就不会设置系统代理

![image](https://user-images.githubusercontent.com/16284775/75223284-10d6eb80-57e1-11ea-9f5b-d1766c347060.png)

**Comment by TheWanderingCoel** [comment]
换个服务器试试？

**Comment by lwmxiaobei** [comment]
> 换个服务器试试？

换了好几个都不行😭

**Comment by TheWanderingCoel** [comment]
批量倒入的么，试试手动输入密码试试？实在不行试试cli？
