### ISSUE TITLE
1.3升级后永远打不开了！！！你的配置已由旧版Trojan-Qt5升级。 一个纯净安装是必须的。 请参阅wiki获得更多信息。

### ISSUE THREAD

**Issue by wulei** [Trojan-Qt5/Trojan-Qt5#383]
### 简要描述问题

从老版本升级，就一直报这个错误，无法打开：
你的配置已由旧版Trojan-Qt5升级。
一个纯净安装是必须的。
请参阅wiki获得更多信息。

### 环境

- Trojan-Qt5 版本：1.3
- 操作系统版本：macos

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by wulei** [comment]
wiki中好像没找到如何解决升级配置问题，打开多次还是一样的问题

**Comment by DuckSoft** [comment]
咳，都说了要纯净安装，你把之前的配置文件都扬了不就可以了吗。

**Comment by wulei** [comment]
macos我都不知道他配置文件保存在哪，知道我就去删了

**Comment by wulei** [comment]
> 咳，都说了要纯净安装，你把之前的配置文件都扬了不就可以了吗。

macos我都不知道他配置文件保存在哪，知道我就去删了

**Comment by GickThomas** [comment]
重新安装旧版本的trojan-qt5，把里面的配置删除，卸载旧版本，安装新版本。

**Comment by Mmmmjnh** [comment]
> > 咳，都说了要纯净安装，你把之前的配置文件都扬了不就可以了吗。
> 
> macos我都不知道他配置文件保存在哪，知道我就去删了

配置文件在 ~/.config目录下
