### ISSUE TITLE
以后发布新版本前能不能先经过Apple的公证(Notarizing) 要求？

### ISSUE THREAD

**Issue by hugbio** [Trojan-Qt5/Trojan-Qt5#385]
以后发布新版本前能不能先经过Apple的公证(Notarizing) 要求？

**Comment by TheWanderingCoel** [comment]
@hugbio 开源免费项目为何要这么做？如果您对软件安全不具有信心，请卸载。

**Comment by DuckSoft** [comment]
请你看一下隔壁 Krita 的情况：
https://krita.org/zh/item/first-notarized-macos-build-of-krita-zh/

**Comment by xhrm** [comment]
> 以后发布新版本前能不能先经过Apple的公证(Notarizing) 要求？

开源免费项目没有那个必要，如果对安全性不放心可以放弃使用或自己编译打包~
