### ISSUE TITLE
你的配置已由旧版Trojan-Qt5升级。 一个纯净安装是必须的。 请参阅wiki获得更多信息。

### ISSUE THREAD

**Issue by raymondronaldo** [Trojan-Qt5/Trojan-Qt5#387]
这个问题怎么解决呢？MAC安装最新的v1.3.1遇到的

**Comment by iambonboncat** [comment]
出现同样都问题了！！

**Comment by iambonboncat** [comment]
重启无效！

**Comment by CannotTell** [comment]
同样问题，目前退回1.2版本

**Comment by TheWanderingCoel** [comment]
@CannotTell 把config.ini删了不就行了？？？

**Comment by CannotTell** [comment]
> @CannotTell 把config.ini删了不就行了？？？

请问大佬 这个config.ini文件在哪里？感谢

**Comment by VIKI623** [comment]
+1

**Comment by raymondronaldo** [comment]
> @CannotTell 把config.ini删了不就行了？？？

程序都删了，还是不行

**Comment by SimonLuoshiping** [comment]
我也是这样的问题死活打不开。

**Comment by yhll** [comment]
~/.config/trojan-qt5/config.ini

**Comment by SimonLuoshiping** [comment]
@yhll 我把程序都删除了，还是不行，还是有这个提示。

**Comment by SimonLuoshiping** [comment]
@TheWanderingCoel 已把程序都删除了，用clenan MYMAC X删除的，还是有提示

**Comment by TheWanderingCoel** [comment]
@SimonLuoshiping rm -rf ~/.config/trojan-qt5不就好了？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by pineapplejs** [comment]
~/.config/trojan-qt5 删除就好了

**Comment by raymondronaldo** [comment]
> @SimonLuoshiping rm -rf ~/.config/trojan-qt5不就好了？？？？？？？？？？？？？？？？？？？？？？？？

成功了，感谢

**Comment by zhoujian365** [comment]
> @SimonLuoshiping rm -rf ~/.config/trojan-qt5不就好了？？？？？？？？？？？？？？？？？？？？？？？？

这个路径能不能加到这个报错弹窗上。应该非常多的人都不知道配置文件在这
