### ISSUE TITLE
Trojan-Qt5 Windows 版本导入 gui-config.json 连接，不能设置连接 类型

### ISSUE THREAD

**Issue by ijliym** [Trojan-Qt5/Trojan-Qt5#391]
### 简要描述问题
大概从 v1.0.4 之后的版本开始，`从 gui-config.json 导入连接` 后，连接类型一直没有设置，之前的版本是 “TROJAN”。
连接类型没有默认设置，可以连接，显示连接成功，但是没有效果（不能连网），也不能编辑。

如下图所示
![image](https://user-images.githubusercontent.com/43025881/86474426-5f8b2800-bd75-11ea-923a-24a78935a57c.png)

### 环境
- Trojan-Qt5 版本：`v1.1.0` ～ `v1.3.1`
- 操作系统版本：Windows 10

### 操作步骤
从菜单 `文件` | `从 gui-config.json 导入连接`。

### 期望的结果
设置连接类型为 `TROAJN`。

### 实际结果
设置连接类型为 “UNKNOWN”。

### 配置文件和日志文件（请隐去敏感信息）

```json
{
    "configs": [
        {
            "server": "fm1-1.sstr-api.xyz",
            "server_port": 443,
            "password": "***",
            "tcp_fast_open": false,
            "verify": true,
            "verify_certificate": true,
            "verify_hostname": true,
            "remarks": "\u7f8e\u56fd-FM1-1,\u6d41\u91cf\u500d\u7387:1.00"
        },
		...
        {
            "server": "v6-3.sstr-api.xyz",
            "server_port": 443,
            "password": "***",
            "tcp_fast_open": false,
            "verify": true,
            "verify_certificate": true,
            "verify_hostname": true,
            "remarks": "\u65e5\u672c-V6-3,\u6d41\u91cf\u500d\u7387:1.00"
        }
    ]
}
```

```
两个日志文件 `core.log` 和 `gui.log` 都没有内容。
```

**Comment by TheWanderingCoel** [comment]
@ijliym 从老版本的gui-config导入是不被接受的

**Comment by ijliym** [comment]
从 http://shadowsocks-links.com/portal 上下载的不应该不接受吧？而且其他的列都可以，就这个类型不接受，总觉得是个问题。

**Comment by TheWanderingCoel** [comment]
@ijliym 他们的版本很老了，请使用订阅链接而不是guiconfig

**Comment by ijliym** [comment]
哦，好的，我看看。

**Comment by ijliym** [comment]
订阅的链接不知道在哪里使用，还有二维码。
![image](https://user-images.githubusercontent.com/43025881/86477038-3b7e1580-bd7a-11ea-8250-72e5b1ccaa56.png)

**Comment by ijliym** [comment]
看到了，多谢！
