### ISSUE TITLE
希望增加打开软件自动连接上次使用节点的功能

### ISSUE THREAD

**Issue by wangyz1997** [Trojan-Qt5/Trojan-Qt5#393]
**Is your feature request related to a problem? Please describe.**
不。

**Describe the solution you'd like**
希望增加打开软件自动连接上次使用节点的功能，在与开机自启的功能配合的时候，不用每次开机都要重新选一次节点。

**Describe alternatives you've considered**
无。

**Additional context**
无。

**Comment by TheWanderingCoel** [comment]
@wangyz1997 “自动化”按钮

**Comment by wangyz1997** [comment]
@TheWanderingCoel 感谢，在节点的设置界面找到了。
