### ISSUE TITLE
最新版本安装完添加服务器订阅并自定义设置后退出，重启程序后所有订阅自动清空，所有自定义设置全部还原成默认。

### ISSUE THREAD

**Issue by YFTX2015** [Trojan-Qt5/Trojan-Qt5#394]
### 环境

- Trojan-Qt5 版本：
- 操作系统版本：

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by TheWanderingCoel** [comment]
@YFTX2015 如果您不提供系统，软件版本，以及之前进行过的操作，该问题将被立即关闭。

**Comment by YFTX2015** [comment]
系统win10专业工作站版insider preview build 20161.rs_prerelease.200627-1754，软件版本已经说过，是最新版，只不过我懒得说明编号罢了。我认为作者应该十分清楚最新版具体指的是哪个版本，毕竟我没有看到测试版，那最新版只可能是唯一的，因此我认为没得必要还要把编号报出来。此程序我之前曾安装过多次，因为自定义设置不当导致运营商提供的线路连不起，软件又没得一键恢复默认设置功能，因此不得不卸载重装。说到卸载，顺便提下，进到程序安装目录，双击程序自带的卸载文件，也只是把这个卸载文件本身跟桌面快捷方式删除罢了，其它的文件原方不动还在那里。后来重装再次卸载，换成鼠标右键管理员模式运行，照样只能删除卸载文件本身，而软件并未卸载。虽然通过了删除软件所在的整个文件夹的方式，但并不能保证就把此程序彻底卸载干净。本人判断，这个因素跟之后出现的一系列问题有脱不开的关系。最后吐槽下此软件，它跟V2RayN，Qv2ray都不一样，自定义设置除非自己很懂，否则哪怕改一个地方的数据都会导致连不起，也就是说对于小白来讲，只有默认设置才能正常连接。事实上我第一遍安装后是能够正常使用的。而本人虽是小白，但有抱着好奇心的心态喜欢去捣鼓软件的设置，虽然避免不了失败，但相信重装都能解决问题。上面提到的V2RayN, Qv2ray本身在自定义设置上就没得那么多的限制，即使改错一些地方，都还能连得起，而且卸载也很干净，重装后的后续操作也不会产生任何问题。相比之下，此Trojan-Qt5经过卸载重装后，会出现不少问题，标题提到的那几个问题还不是全部，不过其它的不提也罢，因为严重性远没得标题提到的那几个程度高，导致无法使用。
