### ISSUE TITLE
linux cpu占用过高

### ISSUE THREAD

**Issue by doswo** [Trojan-Qt5/Trojan-Qt5#401]
### 简要描述问题
CPU占用过高，打开风扇就加速。

### 环境

- Trojan-Qt5 版本：1.3.1
- 操作系统版本：5.4.0-kali-amd64 debian 5.4.19-kali

### 操作步骤
打开客户端，连接节点

### 期望的结果
安静运行

### 实际结果
cpu占用较高，风扇加速

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by idnsunset** [comment]
Debian sid 上 libgrpc++1 v1.26 有一个 infinite looping 的 bug (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959675)，或许与此有关系。

**Comment by doswo** [comment]
> Debian sid 上 libgrpc++1 v1.26 有一个 infinite looping 的 bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959675
> 或许与此有关系。

## 感谢您的回复
似乎是这样的，但是，似乎在目前的各大源里面还没有更新这个软件包，在手动更替版本之后，出现了启动时崩溃的现象，但是，由于期间操作了其他软件包，并不确定是否这个库引起问题，目前已经更换客户端，就不继续研究了。感谢您的回复！

**Comment by idnsunset** [comment]
> > Debian sid 上 libgrpc++1 v1.26 有一个 infinite looping 的 bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959675
> > 或许与此有关系。
> 
> ## 感谢您的回复
> 似乎是这样的，但是，似乎在目前的各大源里面还没有更新这个软件包，在手动更替版本之后，出现了启动时崩溃的现象，但是，由于期间操作了其他软件包，并不确定是否这个库引起问题，目前已经更换客户端，就不继续研究了。感谢您的回复！

我不确定 Kali 是基于 Debian 的哪个 branch，还有你是用的 Deb 包还是 AppImage？我是升级 stable 到 sid，然后安装了最新的 Deb 包产生 100% cpu 占用的问题，一开始还没注意到风扇的声音。libgrpc++1 v1.26 的 bug 在 1.29 版本中 fixed 了，不过目前还在 experimental ，尚未进入 sid。
