### ISSUE TITLE
win10 用新版本的Trojan-QT5无法打开google

### ISSUE THREAD

**Issue by qsxing** [Trojan-Qt5/Trojan-Qt5#412]
[INFO]  2020/07/12 10:19:25 Conn tunneling to www.googleapis.com:443
[DEBUG] 2020/07/12 10:19:25 github.com/p4gefau1t/trojan-go/proxy/client.(*Client).handleSocksConn:client.go:95 Policy 0
[DEBUG] 2020/07/12 10:19:26 github.com/p4gefau1t/trojan-go/proxy/client.(*TLSManager).dialTLSWithFakeFingerprint:tls.go:380 Fingerprint firefox failed, err: x509: certificate has expired or is not yet valid: 
[DEBUG] 2020/07/12 10:19:26 github.com/p4gefau1t/trojan-go/proxy/client.(*TLSManager).dialTLSWithFakeFingerprint:tls.go:380 Fingerprint chrome failed, err: x509: certificate has expired or is not yet valid: 
[ERROR] 2020/07/12 10:19:26 github.com/p4gefau1t/trojan-go/proxy/client.(*TLSManager).dialTLSWithFakeFingerprint:tls.go:372 Failed to set ios fingerprint | tls: CurvePreferences includes unsupported curve
[ERROR] 2020/07/12 10:19:26 github.com/p4gefau1t/trojan-go/proxy/client.(*Client).handleSocksConn:client.go:111 Failed to init transport layer | All client hello IDs tried but failed

后台日志一直显示上面的日志，无法打开google和youtube，请问是什么问题？

**Comment by qsxing** [comment]
问题解决，是trojan服务器端证书过期导致的，需要重新修复一下证书即可。
运行一键脚本，选择4.修复证书

**Comment by LuckyLi706** [comment]
where is the script.i can not find it.please tell thank you.

**Comment by qsxing** [comment]
the install script is here :

https://raw.githubusercontent.com/atrandys/trojan/master/trojan_mult.sh

**Comment by LuckyLi706** [comment]
thank you，you are a good man。


qsxing <notifications@github.com> 于2020年7月14日周二 下午1:55写道：
