### ISSUE TITLE
Trojan-Go v0.8.0 WebSocket 的 hostname 已经改成 host 了

### ISSUE THREAD

**Issue by peter-tank** [Trojan-Qt5/Trojan-Qt5#414]
没有同步变更配置，指定域名 IP 的 WebSocket 连接将不能正常连接。
https://github.com/Trojan-Qt5/Trojan-Qt5/blob/2a50830bf74890a687eae243583aa6fe8ef26896/src/confighelper.cpp#L1074

**Comment by TheWanderingCoel** [comment]
@peter-tank trojan-go那边可真能改啊，收到了，感谢反馈。

**Comment by peter-tank** [comment]
至少目前 cipher_tls13 也合并到 cipher_tls 了

**Comment by TheWanderingCoel** [comment]
@peter-tank 我不知道该说什么好。。。trojan-go真神奇

**Comment by KevinZonda** [comment]
@peter-tank
