### ISSUE TITLE
安装后打开程序出错

### ISSUE THREAD

**Issue by feixiang-1** [Trojan-Qt5/Trojan-Qt5#418]
### 环境

- Trojan-Qt5 版本：V1.4.0
- 操作系统版本：windows7 x64

### 操作步骤
下载了https://github.com/Trojan-Qt5/Trojan-Qt5/releases/download/v1.4.0/Trojan-Qt5-Windows.exe
安装完毕打开 trojan-qt5.exe

### 实际结果
![image](https://user-images.githubusercontent.com/35004327/87398578-a33d2780-c5e8-11ea-859b-b56bbb655439.png)

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by TheWanderingCoel** [comment]
@feixiang-1 请使用.zip, .7z
