### ISSUE TITLE
请问手动添加ss节点的问题

### ISSUE THREAD

**Issue by causlayer** [Trojan-Qt5/Trojan-Qt5#419]
### 简要描述问题
手动添加ss节点时不知道如何填写插件和插件参数，
![E02C1D98-CF95-42DB-AC9F-993B48554773](https://user-images.githubusercontent.com/7320355/87405447-0a130e80-c5f2-11ea-8d5d-72b109b252d5.png)

### 环境

- Trojan-Qt5 版本：1.4.0
- 操作系统版本：mac os 10.15.5

### 操作步骤
连接-添加-手动-手动添加ss

### 期望的结果
可以正常使用

### 实际结果
无法翻墙

### 配置文件和日志文件（请隐去敏感信息）
还没连接，无法获取到日志，已经看了核心日志没有内容
```
在此粘贴日志
```

**Comment by studentmain** [comment]
请参考插件自己的使用说明

**Comment by causlayer** [comment]
谢谢，已转用clashX。
