### ISSUE TITLE
通过gui-config.json导入配置，关闭软件重新打开，导入的配置没没被保留

### ISSUE THREAD

**Issue by YiiGuxing** [Trojan-Qt5/Trojan-Qt5#422]
### 简要描述问题
通过gui-config.json导入配置，关闭软件重新打开，导入的配置没没被保留，配置列表为空。

### 环境

- Trojan-Qt5 版本：v1.4.1
- 操作系统版本：win10

**Comment by TheWanderingCoel** [comment]
@YiiGuxing 请使用.zip，.7z

**Comment by YiiGuxing** [comment]
OK，可以了，谢谢
