### ISSUE TITLE
socks5的端口就是不监听

### ISSUE THREAD

**Issue by ningchen78** [Trojan-Qt5/Trojan-Qt5#425]
用了一个很老的版本，大概是1.0或者啥（因为升级全删了，无法确切知道了），升级到最新的1.4.1，然后就发现不论怎么样，包括改端口，socks5的端口就是不起来，重启系统和重启trojan-qt5都没有用，其他端口是起来的，58591，54400都是好的，我是win10系统，在资源监视器里查看trojan-qt5的所有监听端口，应该不会错，也确实用不了

**Comment by TheWanderingCoel** [comment]
@ningchen78 什么类型？trojan/ss/ssr/vmess/snell?核心日志看了吗

**Comment by ningchen78** [comment]
核心日志里没有东西，类型是trojan，不过你这一说我注意到软件主界面显示的unkown，配置都是通过jason导进来的，如下是其中一个server的示例，可能和这个有关系，我再看看。

            "server": "***-*.sstr-api.xyz",
            "server_port": 443,
            "password": "********************",
            "tcp_fast_open": false,
            "verify": true,
            "verify_certificate": true,
            "verify_hostname": true,
            "remarks": "AU,\u6d41\u91cf\u500d\u7387:1.00"

**Comment by TheWanderingCoel** [comment]
@ningchen78 旧版配置不被支持，如果你是从某机场的gui-config.json导入，请考虑使用订阅

**Comment by ningchen78** [comment]
好了，是这个问题，不从gui-config.json导，改成订阅就好了，谢谢！
