### ISSUE TITLE
vmess parser 应在 "net" 为空白时默认当做 tcp 处理

### ISSUE THREAD

**Issue by phlinhng** [Trojan-Qt5/Trojan-Qt5#427]
### 环境

- Trojan-Qt5 版本：v1.4.0
- 操作系统版本：

### 操作步骤
phlinhng/v2ray-tcp-tls-web#28
> 分享链接里"net":""未标明传输协议类型，v2rayN默认当作TCP对待，但是Trojan-QT5等客户端严格按照分享链接里的传输协议类型执行，咱链接里的传输协议类型为空，导致错误。

### 期望的结果
当分享链接未标明传输层协议时，应视为裸 vmess 也就是 `tcp`，而不是强制指定 `tcp` 。v2RayN 和 Shadowrokcet 都支持 net 为空的写法，考量 v2RayN 是 vmess 格式的制定者，Trojan-Qt5 的 parser 理应和 v2RayN 一致。

**Comment by Qv2ray-dev** [comment]
`net ：传输协议（tcp\kcp\ws\h2\quic)` 并未说明 net 可以为空值

**Comment by phlinhng** [comment]
在 Shadowrocket 和 v2RayN 中，net 为空或是非法数值时会嘗试以 `tcp` 连接，兼容这种写法会比较 robust。

**Comment by U-v-U** [comment]
给个建议 @phlinhng https://github.com/v2ray/discussion/issues/720

**Comment by phlinhng** [comment]
这个 issue 是希望兼容 2dust vmess 的非规范写法，因为你不晓得现在网上到底有多少没写 net 的订阅连接在流传。未来我也是支持 v2ray/discussion#720 订一个官方的、可读性更高的 vmess url scheme 来替换过时的 2dust vmess。但是在 2dust vmess 还在被广泛使用的时候，制定者自己开发的客户端都容许这种写法了，其他借用这个标准的客户端却拿着几百年没更新的简陋文档觉得应该要强制指定 net 类型，从常识上说不过去。

**Comment by U-v-U** [comment]
@phlinhng 那首先我建议 2dust 更新文档

**Comment by phlinhng** [comment]
> @phlinhng 那首先我建议 2dust 更新文档

从 2dust 对 issue 的态度来看，他短期内不会去修那个标准了。既然要启用新 url，与其期待他更新文档，不如当作历史遗留问题加个 net 的默认类型就好兼容一下就好。等新 url 普及了，如果新 url 强制要求填写传输类型，就照新的标准来。

**Comment by TheWanderingCoel** [comment]
@phlinhng 有空加一下，新标准暂时没考虑加入

**Comment by phlinhng** [comment]
@TheWanderingCoel 感谢！
