### ISSUE TITLE
关于代理类型的问题

### ISSUE THREAD

**Issue by Mr-Daemon** [Trojan-Qt5/Trojan-Qt5#430]
### 简要描述问题

请问trojan客户端设置的代理是全局检测http/https请求并代理吗，如果设置了全局代理，在terminal(oh-my-zsh)里面比如homebrew的下载更新请求是否会走代理呢。我已经阅读了Q&A里面关于ping命令的tcp流量不会代理的问题了。

### 环境

- Trojan-Qt5 版本：1.4.0
- 操作系统版本：macOS Catalina 10.15.5

### 操作步骤

homebrew install <target_package>

### 期望的结果

下载流量通过代理

### 实际结果

速度很慢

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by TheWanderingCoel** [comment]
@Mr-Daemon 并不是，请使用复制终端代理命令

**Comment by Mr-Daemon** [comment]
> @Mr-Daemon 并不是，请使用复制终端代理命令

请问“终端代理命令”是需要配置trojan吗，在FAQ&README里面没有找到相关内容

**Comment by TheWanderingCoel** [comment]
@Mr-Daemon 托盘图标，右键

**Comment by Mr-Daemon** [comment]
> @Mr-Daemon 托盘图标，右键

找了，感谢
