### ISSUE TITLE
建议增加一个15分钟全局模式功能

### ISSUE THREAD

**Issue by Zhou-Yucheng** [Trojan-Qt5/Trojan-Qt5#432]
首先感谢作者开发的该软件！

在最常用的PAC模式下，偶尔会遇到一些网站打不开，就得手动切换为全局模式的情况 。但是用了全局模式很容易忘记切换回PAC，又可能会造成流量浪费，或一些ip检测异常的情况（比如登录邮箱或部分网站时提示ip异常）。有时要折腾一小会才想起是代理忘记切换了。

因此，希望作者在Trojan的托盘右键菜单中，增加一个”15分钟全局模式“功能，能15分钟后自动切换回原来的模式（如PAC）
至于时间是否应该定为15分钟，可以再讨论而定，或允许用户配置

**Comment by xhrm** [comment]
自己动动脑，就不要让开发者折腾无聊的功能了。

**Comment by Zhou-Yucheng** [comment]
我觉得如果能command line调用Trojan也是极好的，但是我没找到。
请问你的解决方案是？

**Comment by TheWanderingCoel** [comment]
@Zhou-Yucheng 这个功能我的需求是0,我也没有见过同类软件有此功能，所以不会添加。而且本项目是库调用而不是command line调用trojan
