### ISSUE TITLE
.zip版本在win10 2004版本上打开时报缺少dll

### ISSUE THREAD

**Issue by C-creator** [Trojan-Qt5/Trojan-Qt5#435]
**版本：** v1.4.0
                  win10 2004

**错误提示截图：**
![image](https://user-images.githubusercontent.com/8022253/87875838-a4b28980-ca06-11ea-83fe-151d083043a5.png)
![image](https://user-images.githubusercontent.com/8022253/87875843-ada35b00-ca06-11ea-9327-c8acc66623b6.png)
![image](https://user-images.githubusercontent.com/8022253/87875847-b562ff80-ca06-11ea-8f30-896be8142bbf.png)
![image](https://user-images.githubusercontent.com/8022253/87875855-bc8a0d80-ca06-11ea-8f24-4315083574f5.png)

**简单描述：**
双击trojan-qt5.exe后依次出现以上四个错误提示。

**Comment by TheWanderingCoel** [comment]
@C-creator 你需要安装32位的c++运行库

**Comment by C-creator** [comment]
> @C-creator 你需要安装32位的c++运行库

好的，多谢解惑。
