### ISSUE TITLE
无网络时启动应用segfault崩溃

### ISSUE THREAD

**Issue by i0ntempest** [Trojan-Qt5/Trojan-Qt5#437]
### 简要描述问题
无网络连接时打开trojan-qt5.app会立即闪退。
### 环境

- Trojan-Qt5 版本：1.4.0
- 操作系统版本：macOS 10.15.6/11.0 beta

### 操作步骤
禁用所有网络接口，启动trojan-qt5应用

### 期望的结果
应用运行

### 实际结果
segfault崩溃

### 配置文件和日志文件（请隐去敏感信息）
崩溃日志文件
[trojan-qt5_2020-07-21-195025-2_iMac.crash.txt](https://github.com/Trojan-Qt5/Trojan-Qt5/files/4957039/trojan-qt5_2020-07-21-195025-2_iMac.crash.txt)

**Comment by i0ntempest** [comment]
刚刚发现几次崩溃进程被kill的信号不并每次都一样。这里有另外几个日志
[trojan-qt5_2020-07-21-195025_iMac.crash.txt](https://github.com/Trojan-Qt5/Trojan-Qt5/files/4957054/trojan-qt5_2020-07-21-195025_iMac.crash.txt)
[trojan-qt5_2020-07-21-195025-1_iMac.crash.txt](https://github.com/Trojan-Qt5/Trojan-Qt5/files/4957055/trojan-qt5_2020-07-21-195025-1_iMac.crash.txt)

**Comment by TheWanderingCoel** [comment]
已定位，晒后修复

**Comment by TheWanderingCoel** [comment]
已在最新commit修复
