### ISSUE TITLE
关闭QT5之后,重新开没有新保存的节点

### ISSUE THREAD

**Issue by Stone642** [Trojan-Qt5/Trojan-Qt5#445]
### 简要描述问题
添加新的节点,重启软件之后,就不会保存.就算是删除旧的节点,重新开始还是有的.有点像恢复到某一天的状态
### 环境

- Trojan-Qt5 版本：1.40
- 操作系统版本：win10

### 配置文件和日志文件（请隐去敏感信息）

```
在此粘贴日志
```

**Comment by TheWanderingCoel** [comment]
@Stone642 请使用.zip .7z版本
