### ISSUE TITLE
enhancement: 自动检测新版本功能

### ISSUE THREAD

**Issue by babylife** [Trojan-Qt5/Trojan-Qt5#46]
可否添加自动或者手动检测新版本的功能？当然，在线更新就更加完美了

**Comment by TheWanderingCoel** [comment]
有想过，但没有什么好的解决方案。``fervor``界面太老旧，``sparkle``只支持macos

**Comment by TheWanderingCoel** [comment]
找到一个不错的方法，此feature不会支持linux
