### ISSUE TITLE
Mac 更新0.0.4后

### ISSUE THREAD

**Issue by wd1719** [Trojan-Qt5/Trojan-Qt5#50]
点connecte没有反应
log显示1081 being used

**Comment by TheWanderingCoel** [comment]
检查端口是否有别的软件在占用。``lsof -i:1081``

**Comment by wd1719** [comment]
输入命令后,没有显示

![Xnip2020-02-22_21-45-21.jpg](https://i.loli.net/2020/02/22/s9fxCjUDkFavO1Z.jpg)
我系统问题?

**Comment by TheWanderingCoel** [comment]
试试强制连接？明明端口没有占用。

**Comment by wd1719** [comment]
查了1080被V2Ray占用,但我根本没有启动V2ray, kill进程,重启,暂时没有遇到问题
感谢支持

**Comment by VEI7** [comment]
我也是1080被V2Ray占用，但我kill进程后又开了个新进程，新的PID

**Comment by TheWanderingCoel** [comment]
尝试换下服务器的socks5和http port端口？每个服务器都可以单独设置

**Comment by TheWanderingCoel** [comment]
请尝试004a
