### ISSUE TITLE
建议添加两项功能

### ISSUE THREAD

**Issue by EA-DICE** [Trojan-Qt5/Trojan-Qt5#67]
像Shadowsocks那样，增加一项定期测速（丢包，延迟等）的功能。并且建议增加手动更新PAC的功能。十分感谢作者的付出与贡献。

**Comment by TheWanderingCoel** [comment]
会加入，但是不一定很快能实现。手动PAC应该能很快实现。

**Comment by EA-DICE** [comment]
好的，万分感谢

**Comment by TheWanderingCoel** [comment]
支持了多种pac模式,手动还需要研究

**Comment by EA-DICE** [comment]
好的，感谢作者的辛勤付出

**Comment by EA-DICE** [comment]
这个版本属实惊艳了我，希望作者保重身体，健康第一，再次感谢你为大家做出的贡献！

**Comment by TheWanderingCoel** [comment]
> 这个版本属实惊艳了我，希望作者保重身体，健康第一，再次感谢你为大家做出的贡献！

感谢支持！
