### ISSUE TITLE
断开连接时弹出 10 次修改网络 prompt

### ISSUE THREAD

**Issue by TabrisK** [Trojan-Qt5/Trojan-Qt5#76]
我只在第一次输入了密码，后面几次全部点取消，最后正常完成了断连操作。

System:
MacOS Sierra 10.12.6
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
Trojan-Qt5@0.0.3

**Comment by TheWanderingCoel** [comment]
我这里并不会弹出prompt,旧版系统有限制么？

**Comment by TabrisK** [comment]
> 我这里并不会弹出prompt,旧版系统有限制么？

我觉得不是版本问题。prompt 提示信息是 「”networksetup“正在尝试修改系统网络配置。请输入密码允许此次操作」

我记得昨天下载这个软件以后，系统提示我这个软件 "来自未被认可的开发者"。
经过我的特别许可以后，这个软件才得以正常运行。
这是我的 系统偏好设置-安全性与隐私 界面
<img width="668" alt="WX20200224-141725@2x" src="https://user-images.githubusercontent.com/12509010/75132056-79a26300-5710-11ea-81f5-9452612165ef.png">

另外的，连接的时候也会弹出一样的 prompt，而且我发现 prompt 输不输入密码连接、断连都一样会成功。prompt 弹出次数也是随机的，最近几次试下来分别弹出 6, 12, 10次。

**Comment by TheWanderingCoel** [comment]
系统代理是通过popen调用networksetup设置的，我这里运行不会弹出prompt，不知道什么情况，我有空研究下。可以把自动设置系统代理关掉

**Comment by TheWanderingCoel** [comment]
今天看到另外一个issue也是，也使用的10.12系统，感觉10.12的系统有点问题。调用networksetup需要管理员密码

**Comment by TheWanderingCoel** [comment]
commit已修复，下个版本推送
